---
# See `user.yaml` for more docs on these yaml files.
!include ../includes.yaml
name: custom_field_settings
comment: |
  
  Custom fields are attached to a particular project with the Custom
  Field Settings resource. This resource both represents the many-to-many join
  of the Custom Field and Project as well as stores information that is relevant to that
  particular pairing; for instance, the `is_important` property determines
  some possible application-specific handling of that custom field (see below)

properties:

  - name: id
    <<: *PropType.Id
    comment: |
      Globally unique ID of the custom field.

  - name: created_at
    <<: *PropType.DateTime
    access: Read-only
    comment: |
      The time at which this custom field was created.

  - name: is_important 
    <<: *PropType.Bool 
    access: Read-only 
    comment: |

      `is_important` is a flag that can be used in application-defined
      behavior: for instance, in the Asana web application, `is_important` is
      used to determine if this custom field on this project gets its own
      column when viewed in the project list.



action_classes:
  - name: Get a custom field setting
    url: get-single
  - name: Query for custom field settings
    url: query-settings

actions:

  # Create, Retrieve, Update, Delete

  - name: findById
    class: get-single
    method: GET
    path: "/custom_field_settings/%s"
    params:
      - name: custom_field_setting
        <<: *Param.CustomFieldSettingsId
        required: true
        comment: the ID of the custom field setting.
    comment: |
      Returns the custom_field_settings object which provides information on how a custom field is used with a project.

  - name: findByProject
    class: query-settings
    method: GET
    path: "/projects/%s/custom_field_settings"
    params:
      - name: project
        <<: *Param.ProjectId
        required: true
        comment: The ID of the project for which to list custom field settings
    comment: |
      Returns a list of all of the custom fields settings on a project.
