---
# See `user.yaml` for more docs on these yaml files.
!include ../includes.yaml
name: custom_field_settings
comment: |

  Custom fields are applied to a particular project or portfolio with the
  Custom Field Settings resource. This resource both represents the
  many-to-many join of the Custom Field and Project or Portfolio as well as
  stores information that is relevant to that particular pairing; for instance,
  the `is_important` property determines some possible application-specific
  handling of that custom field and parent.

properties:

  - name: id
    <<: *PropType.Id
    comment: |
      Globally unique ID of the custom field settings object.
      **Note: This field is under active migration to the [`gid` field](#field-gid)--please see our [blog post](/developers/documentation/getting-started/deprecations) for more information.**
  - name: gid
    <<: *PropType.Gid
    comment: |
      Globally unique ID of the custom field settings object.
  - name: resource_type
    <<: *PropType.ResourceType
    comment: |
      The resource type of this resource. The value for this resource is always `custom_field_setting`
    example_values:
      - '"custom_field_setting"'
    values:
      - name: custom_field_setting
        comment: A custom_field_setting resource type.
  - name: created_at
    <<: *PropType.DateTime
    access: Read-only
    comment: |
      The time at which this custom field setting was created.
  - name: is_important
    <<: *PropType.Bool
    access: Read-only
    comment: |
      `is_important` is used in the Asana web application to determine if this
      custom field is displayed in the task list (left pane) of a project. A
      project can have a maximum of 5 custom field settings marked as
      `is_important`.
  - name: parent
    <<: *PropType.CustomFieldSettingsParent
    comment: |
      The parent to which the custom field is applied. This can be a project
      or portfolio and indicates that the tasks or projects that the parent
      contains may be given custom field values for this custom field.
  - name: project
    <<: *PropType.Project
    comment: |
      **Deprecated: new integrations should prefer the `parent` field.**
      The id of the project that this custom field settings refers to.
  - name: custom_field
    access: Read-only
    <<: *PropType.CustomField
    comment: |
      The custom field that is applied to the `parent`.



action_classes:
  - name: Query for custom field settings on a project
    url: query-project-settings
  - name: Query for custom field settings on a portfolio
    url: query-portfolio-settings

actions:

  # Create, Retrieve, Update, Delete

  - name: findByProject
    class: query-project-settings
    method: GET
    path: "/projects/%s/custom_field_settings"
    params:
      - name: project
        <<: *Param.ProjectGid
        required: true
        comment: The ID of the project for which to list custom field settings
    collection: true
    comment: |
      Returns a list of all of the custom fields settings on a project.

  - name: findByPortfolio
    class: query-portfolio-settings
    method: GET
    path: "/portfolios/%s/custom_field_settings"
    params:
      - name: portfolio
        <<: *Param.PortfolioGid
        required: true
        comment: The ID of the portfolio for which to list custom field settings
    collection: true
    comment: |
      Returns a list of all of the custom fields settings on a portfolio.

