---
# See `user.yaml` for more docs on these yaml files.
!include ../includes.yaml
name: custom_field_settings
comment: |

  Custom fields are attached to a particular project with the Custom
  Field Settings resource. This resource both represents the many-to-many join
  of the Custom Field and Project as well as stores information that is relevant to that
  particular pairing; for instance, the `is_important` property determines
  some possible application-specific handling of that custom field (see below)

properties:

  - name: id
    <<: *PropType.Id
    comment: |
      Globally unique ID of the custom field settings object.
  - name: created_at
    <<: *PropType.DateTime
    access: Read-only
    comment: |
      The time at which this custom field was created.
  - name: is_important
    <<: *PropType.Bool
    access: Read-only
    comment: |
      `is_important` is a flag that can be used in application-defined
      behavior: for instance, in the Asana web application, `is_important` is
      used to determine if this custom field on this project is displayed in a
      column when viewed in the project list.
  - name: project
    <<: *PropType.Project
    comment: |
      The id of the project that this custom field settings refers to.
  - name: custom_field
    access: Read-only
    <<: *PropType.CustomField
    comment: |
      The custom field that this custom field settings refers to.



action_classes:
  - name: Query for custom field settings
    url: query-settings

actions:

  # Create, Retrieve, Update, Delete

  - name: findByProject
    class: query-settings
    method: GET
    path: "/projects/%s/custom_field_settings"
    params:
      - name: project
        <<: *Param.ProjectId
        required: true
        comment: The ID of the project for which to list custom field settings
    comment: |
      Returns a list of all of the custom fields settings on a project, in compact form. Note that, as in all queries to collections which return compact representation, `opt_fields` and `opt_expand` can be used to include more data than is returned in the compact representation. See the getting started guide on [input/output options](/developers/documentation/getting-started/input-output-options) for more information.

